# Generated by Django 3.1.7 on 2021-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='rate',
            field=models.CharField(choices=[('1 Star', '1 Star'), ('2 Stars', '2 Stars'), ('3 Stars', '3 Stars'), ('4 Stars', '4 Stars'), ('5 Stars', '5 Stars')], default='5', max_length=10),
        ),
    ]
