# Generated by Django 3.1.7 on 2021-04-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210430_0953'),
        ('customer_feedback', '0002_auto_20210430_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rate',
            field=models.CharField(choices=[('1 Star', '1 Star'), ('2 Stars', '2 Stars'), ('3 Stars', '3 Stars'), ('4 Stars', '4 Stars'), ('5 Stars', '5 Stars')], default='5 Stars', max_length=10),
        ),
    ]
