# Generated by Django 3.1.7 on 2021-04-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_feedback', '0003_auto_20210430_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
