# Generated by Django 3.1.7 on 2021-04-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210430_0953'),
        ('customer_feedback', '0004_auto_20210430_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
    ]
