# Generated by Django 3.1.7 on 2021-05-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210430_0953'),
        ('customer_feedback', '0006_interstedcustomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterstedCustomer',
            new_name='IntrestedCustomer',
        ),
    ]
