# Generated by Django 3.1.7 on 2021-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210430_0953'),
        ('customer_feedback', '0007_auto_20210502_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='product',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='product',
            field=models.ManyToManyField(to='accounts.Product'),
        ),
    ]
