# Generated by Django 3.1.7 on 2021-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210503_2255'),
        ('customer_feedback', '0009_customercomplaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaint',
            name='employee',
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='customer',
            field=models.ManyToManyField(to='accounts.Customer'),
        ),
    ]
