# Generated by Django 3.1.7 on 2021-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210521_1424'),
        ('customer_feedback', '0010_auto_20210503_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaint',
            name='customer',
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='employee',
            field=models.ManyToManyField(to='accounts.Employee'),
        ),
    ]
