# Generated by Django 3.1.7 on 2021-05-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210521_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Friend to Friend', 'Friend to Friend'), ('Twitter', 'Twitter'), ('By Company', 'By Company'), ('LinkedIn', 'LinkedIn')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Working', 'Working'), ('Contacted', 'Contacted'), ('Proposal Sent', 'Proposal Sent'), ('Qualified', 'Qualified'), ('Customer (converted lead)', 'Customer (converted lead)'), ('Closed', 'Closed'), ('Others', 'Others')], max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
