# Generated by Django 3.1.7 on 2021-05-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
    ]
