# Generated by Django 3.1.7 on 2021-05-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_order_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employee',
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
    ]
