# Generated by Django 3.1.7 on 2021-05-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210523_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
