# Generated by Django 3.1.7 on 2021-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
