# Generated by Django 3.1.7 on 2021-05-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='product',
        ),
    ]
