# Generated by Django 3.1.7 on 2021-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210528_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to='', verbose_name='Logo/Photo'),
        ),
    ]
