# Generated by Django 3.1.7 on 2021-05-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210528_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Assigned To'),
        ),
    ]
