# Generated by Django 3.1.7 on 2021-05-28 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210528_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('call_type', models.CharField(choices=[('Call', 'Call'), ('Conference', 'Conference'), ('Skype', 'Skype'), ('WhatsApp', 'WhatsApp')], max_length=255, null=True)),
                ('flag', models.CharField(choices=[('No Answer', 'No Answer'), ('Important', 'Important'), ('Busy', 'Busy'), ('Urgent', 'Urgent'), ('Left message', 'Left message'), ('Reschedule', 'Reschedule')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.call'),
        ),
    ]
