# Generated by Django 3.1.7 on 2021-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
