# Generated by Django 3.1.7 on 2021-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210528_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
