# Generated by Django 3.1.7 on 2021-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210528_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='image',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to=''),
        ),
    ]
