# Generated by Django 3.1.7 on 2021-05-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210528_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='image',
            new_name='img',
        ),
    ]
