# Generated by Django 3.1.7 on 2021-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210528_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='img',
        ),
    ]
