# Generated by Django 3.1.7 on 2021-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_email_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='img',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to=''),
        ),
    ]
