# Generated by Django 3.1.7 on 2021-06-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210602_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='call',
        ),
        migrations.AddField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lead'),
        ),
    ]
