# Generated by Django 3.1.7 on 2021-06-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210602_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contacts'},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lead'),
        ),
    ]
