# Generated by Django 3.1.7 on 2021-06-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210603_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lead'),
        ),
    ]
