# Generated by Django 3.1.7 on 2021-06-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210605_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
