# Generated by Django 3.1.7 on 2021-07-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210630_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Assigned To'),
        ),
    ]
