# Generated by Django 3.1.7 on 2021-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_call_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='lead',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Customer', 'Customer')], max_length=200, null=True),
        ),
    ]
