# Generated by Django 3.1.7 on 2021-07-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20210702_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='opportunity',
        ),
    ]
