# Generated by Django 3.1.7 on 2021-07-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20210703_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('to_time', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('reminder', models.CharField(choices=[('None', 'None'), ('At the time of meeting', 'At the time of meeting'), ('5 minutes before', '5 minutes before'), ('15 minutes before', '15 minutes before'), ('30 minutes before', '30 minutes before'), ('1 hour before', '1 hour before'), ('1 day before', '1 day before')], default='15 minutes before', max_length=255, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
