# Generated by Django 3.1.7 on 2021-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_meeting_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='from_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='to_time',
            field=models.TimeField(null=True),
        ),
    ]
