# Generated by Django 3.1.7 on 2021-07-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20210704_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'meetings'},
        ),
    ]
