# Generated by Django 3.1.7 on 2021-07-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_remove_meeting_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
    ]
