# Generated by Django 3.1.7 on 2021-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20210712_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='img',
            field=models.ImageField(blank=True, default='LOGO.png', null=True, upload_to=''),
        ),
    ]
